# Generated by Codex on 2026-02-11
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                (
                    "currency",
                    models.CharField(choices=[("NAD", "NAD"), ("ZAR", "ZAR")], default="NAD", max_length=3),
                ),
                ("is_negotiable", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("sold", "Sold"), ("archived", "Archived")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="listings", to="catalog.category"),
                ),
                (
                    "city",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="listings", to="locations.city"),
                ),
                (
                    "owner",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listings", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "region",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="listings", to="locations.region"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="listing_status_idx"),
                    models.Index(fields=["category"], name="listing_category_idx"),
                    models.Index(fields=["region"], name="listing_region_idx"),
                    models.Index(fields=["city"], name="listing_city_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=models.Q(("price_amount__gte", 0), ("price_amount__isnull", True), _connector="OR"),
                        name="listing_price_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="listings/%Y/%m/%d/")),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="listings.listing"),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("listing",),
                        name="unique_primary_listing_image",
                    )
                ],
            },
        ),
    ]
